services:
  fastapi-app:
    build: .
    container_name: fast-api-container
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - fastapi-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge