name: CD Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.PRODUCTION_SERVER }} >> ~/.ssh/known_hosts


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Build and Deploy to Production
        run: |
            ssh root@${{ secrets.PRODUCTION_SERVER }} <<< 'EOF'
            echo "Deploying latest changes to production..."
            if [ -d fastapi-book-project ]; then
                cd fastapi-book-project
                git pull origin main
                docker compose down
                docker compose up -d --build
            else
                echo "No existing project directory found"
                git clone https://github.com/GideonIsBuilding/fastapi-book-project.git
                cd fastapi-book-project
                docker compose up -d --build
            fi
            EOF
            echo "Deployed to Production"
